# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pau/feina/UPC/projecte/code/GDAIS/GDAIS-core/ui/instrumenteditor_mainwindow.ui'
#
# Created: Tue Jul  5 22:32:40 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InstrumentEditorMainWindow(object):
    def setupUi(self, InstrumentEditorMainWindow):
        InstrumentEditorMainWindow.setObjectName(_fromUtf8("InstrumentEditorMainWindow"))
        InstrumentEditorMainWindow.resize(502, 496)
        self.centralWidget = QtGui.QWidget(InstrumentEditorMainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.instrument_name = QtGui.QLineEdit(self.centralWidget)
        self.instrument_name.setText(_fromUtf8(""))
        self.instrument_name.setObjectName(_fromUtf8("instrument_name"))
        self.gridLayout.addWidget(self.instrument_name, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.instrument_short_name = QtGui.QLineEdit(self.centralWidget)
        self.instrument_short_name.setObjectName(_fromUtf8("instrument_short_name"))
        self.gridLayout.addWidget(self.instrument_short_name, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.byte_order = QtGui.QComboBox(self.centralWidget)
        self.byte_order.setObjectName(_fromUtf8("byte_order"))
        self.byte_order.addItem(_fromUtf8(""))
        self.byte_order.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.byte_order, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.connection = QtGui.QWidget()
        self.connection.setObjectName(_fromUtf8("connection"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.connection)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_4 = QtGui.QLabel(self.connection)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.conn_type = QtGui.QComboBox(self.connection)
        self.conn_type.setEditable(False)
        self.conn_type.setObjectName(_fromUtf8("conn_type"))
        self.conn_type.addItem(_fromUtf8(""))
        self.conn_type.addItem(_fromUtf8(""))
        self.conn_type.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_type)
        self.horizontalLayout.addLayout(self.formLayout_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_16.addLayout(self.horizontalLayout)
        self.conn_serial_group = QtGui.QGroupBox(self.connection)
        self.conn_serial_group.setObjectName(_fromUtf8("conn_serial_group"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.conn_serial_group)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.conn_serial_group)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.conn_serial_port = QtGui.QLineEdit(self.conn_serial_group)
        self.conn_serial_port.setObjectName(_fromUtf8("conn_serial_port"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_serial_port)
        self.label_6 = QtGui.QLabel(self.conn_serial_group)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.conn_serial_baudrate = QtGui.QLineEdit(self.conn_serial_group)
        self.conn_serial_baudrate.setObjectName(_fromUtf8("conn_serial_baudrate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.conn_serial_baudrate)
        self.horizontalLayout_33.addLayout(self.formLayout)
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem3)
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.label_36 = QtGui.QLabel(self.conn_serial_group)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_36)
        self.conn_serial_data_bits = QtGui.QLineEdit(self.conn_serial_group)
        self.conn_serial_data_bits.setObjectName(_fromUtf8("conn_serial_data_bits"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_serial_data_bits)
        self.label_37 = QtGui.QLabel(self.conn_serial_group)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_37)
        self.conn_serial_parity = QtGui.QLineEdit(self.conn_serial_group)
        self.conn_serial_parity.setObjectName(_fromUtf8("conn_serial_parity"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.conn_serial_parity)
        self.label_38 = QtGui.QLabel(self.conn_serial_group)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_38)
        self.conn_serial_stop_bits = QtGui.QLineEdit(self.conn_serial_group)
        self.conn_serial_stop_bits.setObjectName(_fromUtf8("conn_serial_stop_bits"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.FieldRole, self.conn_serial_stop_bits)
        self.horizontalLayout_33.addLayout(self.formLayout_9)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem4)
        self.verticalLayout_16.addWidget(self.conn_serial_group)
        self.conn_tcp_group = QtGui.QGroupBox(self.connection)
        self.conn_tcp_group.setEnabled(False)
        self.conn_tcp_group.setObjectName(_fromUtf8("conn_tcp_group"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.conn_tcp_group)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_8 = QtGui.QLabel(self.conn_tcp_group)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.conn_tcp_host = QtGui.QLineEdit(self.conn_tcp_group)
        self.conn_tcp_host.setObjectName(_fromUtf8("conn_tcp_host"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_tcp_host)
        self.horizontalLayout_34.addLayout(self.formLayout_6)
        spacerItem5 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem5)
        self.formLayout_10 = QtGui.QFormLayout()
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_39 = QtGui.QLabel(self.conn_tcp_group)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_39)
        self.conn_tcp_port = QtGui.QLineEdit(self.conn_tcp_group)
        self.conn_tcp_port.setObjectName(_fromUtf8("conn_tcp_port"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.conn_tcp_port)
        self.horizontalLayout_34.addLayout(self.formLayout_10)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem6)
        self.verticalLayout_16.addWidget(self.conn_tcp_group)
        self.conn_file_group = QtGui.QGroupBox(self.connection)
        self.conn_file_group.setEnabled(False)
        self.conn_file_group.setObjectName(_fromUtf8("conn_file_group"))
        self.formLayout_5 = QtGui.QFormLayout(self.conn_file_group)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_7 = QtGui.QLabel(self.conn_file_group)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.conn_file_name = QtGui.QLineEdit(self.conn_file_group)
        self.conn_file_name.setObjectName(_fromUtf8("conn_file_name"))
        self.horizontalLayout_17.addWidget(self.conn_file_name)
        self.conn_file_name_btn = QtGui.QToolButton(self.conn_file_group)
        self.conn_file_name_btn.setObjectName(_fromUtf8("conn_file_name_btn"))
        self.horizontalLayout_17.addWidget(self.conn_file_name_btn)
        self.formLayout_5.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.verticalLayout_16.addWidget(self.conn_file_group)
        spacerItem7 = QtGui.QSpacerItem(20, 281, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem7)
        self.tabWidget.addTab(self.connection, _fromUtf8(""))
        self.packet_format = QtGui.QWidget()
        self.packet_format.setObjectName(_fromUtf8("packet_format"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.packet_format)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.packet_format)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pf_rx_format_0 = QtGui.QComboBox(self.packet_format)
        self.pf_rx_format_0.setObjectName(_fromUtf8("pf_rx_format_0"))
        self.pf_rx_format_0.addItem(_fromUtf8(""))
        self.pf_rx_format_0.addItem(_fromUtf8(""))
        self.pf_rx_format_0.addItem(_fromUtf8(""))
        self.pf_rx_format_0.addItem(_fromUtf8(""))
        self.pf_rx_format_0.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.pf_rx_format_0)
        self.pf_rx_format_1 = QtGui.QComboBox(self.packet_format)
        self.pf_rx_format_1.setObjectName(_fromUtf8("pf_rx_format_1"))
        self.pf_rx_format_1.addItem(_fromUtf8(""))
        self.pf_rx_format_1.addItem(_fromUtf8(""))
        self.pf_rx_format_1.addItem(_fromUtf8(""))
        self.pf_rx_format_1.addItem(_fromUtf8(""))
        self.pf_rx_format_1.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.pf_rx_format_1)
        self.pf_rx_format_2 = QtGui.QComboBox(self.packet_format)
        self.pf_rx_format_2.setObjectName(_fromUtf8("pf_rx_format_2"))
        self.pf_rx_format_2.addItem(_fromUtf8(""))
        self.pf_rx_format_2.addItem(_fromUtf8(""))
        self.pf_rx_format_2.addItem(_fromUtf8(""))
        self.pf_rx_format_2.addItem(_fromUtf8(""))
        self.pf_rx_format_2.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.pf_rx_format_2)
        self.pf_rx_format_3 = QtGui.QComboBox(self.packet_format)
        self.pf_rx_format_3.setObjectName(_fromUtf8("pf_rx_format_3"))
        self.pf_rx_format_3.addItem(_fromUtf8(""))
        self.pf_rx_format_3.addItem(_fromUtf8(""))
        self.pf_rx_format_3.addItem(_fromUtf8(""))
        self.pf_rx_format_3.addItem(_fromUtf8(""))
        self.pf_rx_format_3.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.pf_rx_format_3)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.label_14 = QtGui.QLabel(self.packet_format)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_8.addWidget(self.label_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.pf_tx_format_0 = QtGui.QComboBox(self.packet_format)
        self.pf_tx_format_0.setObjectName(_fromUtf8("pf_tx_format_0"))
        self.pf_tx_format_0.addItem(_fromUtf8(""))
        self.pf_tx_format_0.addItem(_fromUtf8(""))
        self.pf_tx_format_0.addItem(_fromUtf8(""))
        self.pf_tx_format_0.addItem(_fromUtf8(""))
        self.pf_tx_format_0.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.pf_tx_format_0)
        self.pf_tx_format_1 = QtGui.QComboBox(self.packet_format)
        self.pf_tx_format_1.setObjectName(_fromUtf8("pf_tx_format_1"))
        self.pf_tx_format_1.addItem(_fromUtf8(""))
        self.pf_tx_format_1.addItem(_fromUtf8(""))
        self.pf_tx_format_1.addItem(_fromUtf8(""))
        self.pf_tx_format_1.addItem(_fromUtf8(""))
        self.pf_tx_format_1.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.pf_tx_format_1)
        self.pf_tx_format_2 = QtGui.QComboBox(self.packet_format)
        self.pf_tx_format_2.setObjectName(_fromUtf8("pf_tx_format_2"))
        self.pf_tx_format_2.addItem(_fromUtf8(""))
        self.pf_tx_format_2.addItem(_fromUtf8(""))
        self.pf_tx_format_2.addItem(_fromUtf8(""))
        self.pf_tx_format_2.addItem(_fromUtf8(""))
        self.pf_tx_format_2.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.pf_tx_format_2)
        self.pf_tx_format_3 = QtGui.QComboBox(self.packet_format)
        self.pf_tx_format_3.setObjectName(_fromUtf8("pf_tx_format_3"))
        self.pf_tx_format_3.addItem(_fromUtf8(""))
        self.pf_tx_format_3.addItem(_fromUtf8(""))
        self.pf_tx_format_3.addItem(_fromUtf8(""))
        self.pf_tx_format_3.addItem(_fromUtf8(""))
        self.pf_tx_format_3.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.pf_tx_format_3)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.line_5 = QtGui.QFrame(self.packet_format)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_8.addWidget(self.line_5)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_16 = QtGui.QLabel(self.packet_format)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.pf_start_bytes = QtGui.QListWidget(self.packet_format)
        self.pf_start_bytes.setObjectName(_fromUtf8("pf_start_bytes"))
        self.verticalLayout_2.addWidget(self.pf_start_bytes)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pf_add_start_byte = QtGui.QPushButton(self.packet_format)
        self.pf_add_start_byte.setObjectName(_fromUtf8("pf_add_start_byte"))
        self.horizontalLayout_3.addWidget(self.pf_add_start_byte)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.pf_delete_start_byte = QtGui.QPushButton(self.packet_format)
        self.pf_delete_start_byte.setEnabled(False)
        self.pf_delete_start_byte.setObjectName(_fromUtf8("pf_delete_start_byte"))
        self.horizontalLayout_3.addWidget(self.pf_delete_start_byte)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        spacerItem11 = QtGui.QSpacerItem(80, 50, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_17 = QtGui.QLabel(self.packet_format)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_3.addWidget(self.label_17)
        self.pf_end_bytes = QtGui.QListWidget(self.packet_format)
        self.pf_end_bytes.setObjectName(_fromUtf8("pf_end_bytes"))
        self.verticalLayout_3.addWidget(self.pf_end_bytes)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pf_add_end_byte = QtGui.QPushButton(self.packet_format)
        self.pf_add_end_byte.setObjectName(_fromUtf8("pf_add_end_byte"))
        self.horizontalLayout_2.addWidget(self.pf_add_end_byte)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.pf_delete_end_byte = QtGui.QPushButton(self.packet_format)
        self.pf_delete_end_byte.setEnabled(False)
        self.pf_delete_end_byte.setObjectName(_fromUtf8("pf_delete_end_byte"))
        self.horizontalLayout_2.addWidget(self.pf_delete_end_byte)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.packet_format, _fromUtf8(""))
        self.rx_packets = QtGui.QWidget()
        self.rx_packets.setObjectName(_fromUtf8("rx_packets"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.rx_packets)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.rx_packets_list = QtGui.QListWidget(self.rx_packets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_packets_list.sizePolicy().hasHeightForWidth())
        self.rx_packets_list.setSizePolicy(sizePolicy)
        self.rx_packets_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rx_packets_list.setObjectName(_fromUtf8("rx_packets_list"))
        self.verticalLayout_6.addWidget(self.rx_packets_list)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.rx_packets_add = QtGui.QPushButton(self.rx_packets)
        self.rx_packets_add.setObjectName(_fromUtf8("rx_packets_add"))
        self.horizontalLayout_11.addWidget(self.rx_packets_add)
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.rx_packets_delete = QtGui.QPushButton(self.rx_packets)
        self.rx_packets_delete.setEnabled(False)
        self.rx_packets_delete.setObjectName(_fromUtf8("rx_packets_delete"))
        self.horizontalLayout_11.addWidget(self.rx_packets_delete)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.line_3 = QtGui.QFrame(self.rx_packets)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_13.addWidget(self.line_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.packetNumberLabel = QtGui.QLabel(self.rx_packets)
        self.packetNumberLabel.setObjectName(_fromUtf8("packetNumberLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.packetNumberLabel)
        self.rx_packets_num = QtGui.QLabel(self.rx_packets)
        self.rx_packets_num.setObjectName(_fromUtf8("rx_packets_num"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.rx_packets_num)
        self.label_18 = QtGui.QLabel(self.rx_packets)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.rx_packets_name = QtGui.QLineEdit(self.rx_packets)
        self.rx_packets_name.setObjectName(_fromUtf8("rx_packets_name"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.rx_packets_name)
        self.horizontalLayout_6.addLayout(self.formLayout_2)
        spacerItem14 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line = QtGui.QFrame(self.rx_packets)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_20 = QtGui.QLabel(self.rx_packets)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_5.addWidget(self.label_20)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.rx_packets_fields = QtGui.QTreeWidget(self.rx_packets)
        self.rx_packets_fields.setRootIsDecorated(False)
        self.rx_packets_fields.setObjectName(_fromUtf8("rx_packets_fields"))
        self.rx_packets_fields.header().setDefaultSectionSize(250)
        self.verticalLayout_4.addWidget(self.rx_packets_fields)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rx_packets_add_field = QtGui.QPushButton(self.rx_packets)
        self.rx_packets_add_field.setObjectName(_fromUtf8("rx_packets_add_field"))
        self.horizontalLayout_7.addWidget(self.rx_packets_add_field)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.rx_packets_delete_field = QtGui.QPushButton(self.rx_packets)
        self.rx_packets_delete_field.setEnabled(False)
        self.rx_packets_delete_field.setObjectName(_fromUtf8("rx_packets_delete_field"))
        self.horizontalLayout_7.addWidget(self.rx_packets_delete_field)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.rx_packets, _fromUtf8(""))
        self.tx_packets = QtGui.QWidget()
        self.tx_packets.setObjectName(_fromUtf8("tx_packets"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.tx_packets)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tx_packets_list = QtGui.QListWidget(self.tx_packets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_packets_list.sizePolicy().hasHeightForWidth())
        self.tx_packets_list.setSizePolicy(sizePolicy)
        self.tx_packets_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tx_packets_list.setObjectName(_fromUtf8("tx_packets_list"))
        self.verticalLayout_7.addWidget(self.tx_packets_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.tx_packets_add = QtGui.QPushButton(self.tx_packets)
        self.tx_packets_add.setObjectName(_fromUtf8("tx_packets_add"))
        self.horizontalLayout_12.addWidget(self.tx_packets_add)
        spacerItem17 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.tx_packets_delete = QtGui.QPushButton(self.tx_packets)
        self.tx_packets_delete.setEnabled(False)
        self.tx_packets_delete.setObjectName(_fromUtf8("tx_packets_delete"))
        self.horizontalLayout_12.addWidget(self.tx_packets_delete)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.line_4 = QtGui.QFrame(self.tx_packets)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_14.addWidget(self.line_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.tx_packets)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.tx_packets_num = QtGui.QLabel(self.tx_packets)
        self.tx_packets_num.setObjectName(_fromUtf8("tx_packets_num"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.tx_packets_num)
        self.label_12 = QtGui.QLabel(self.tx_packets)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.tx_packets_name = QtGui.QLineEdit(self.tx_packets)
        self.tx_packets_name.setObjectName(_fromUtf8("tx_packets_name"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.tx_packets_name)
        self.horizontalLayout_9.addLayout(self.formLayout_3)
        spacerItem18 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.line_2 = QtGui.QFrame(self.tx_packets)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_13 = QtGui.QLabel(self.tx_packets)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        spacerItem19 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tx_packets_fields = QtGui.QTreeWidget(self.tx_packets)
        self.tx_packets_fields.setRootIsDecorated(False)
        self.tx_packets_fields.setObjectName(_fromUtf8("tx_packets_fields"))
        self.tx_packets_fields.header().setDefaultSectionSize(250)
        self.verticalLayout_5.addWidget(self.tx_packets_fields)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.tx_packets_add_field = QtGui.QPushButton(self.tx_packets)
        self.tx_packets_add_field.setObjectName(_fromUtf8("tx_packets_add_field"))
        self.horizontalLayout_10.addWidget(self.tx_packets_add_field)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem20)
        self.tx_packets_delete_field = QtGui.QPushButton(self.tx_packets)
        self.tx_packets_delete_field.setEnabled(False)
        self.tx_packets_delete_field.setObjectName(_fromUtf8("tx_packets_delete_field"))
        self.horizontalLayout_10.addWidget(self.tx_packets_delete_field)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tx_packets, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        InstrumentEditorMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(InstrumentEditorMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 502, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        InstrumentEditorMainWindow.setMenuBar(self.menuBar)
        self.action_New = QtGui.QAction(InstrumentEditorMainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Open = QtGui.QAction(InstrumentEditorMainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Save = QtGui.QAction(InstrumentEditorMainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Save_As = QtGui.QAction(InstrumentEditorMainWindow)
        self.action_Save_As.setObjectName(_fromUtf8("action_Save_As"))
        self.action_Quit = QtGui.QAction(InstrumentEditorMainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_About = QtGui.QAction(InstrumentEditorMainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_About)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.instrument_name)
        self.label_2.setBuddy(self.instrument_short_name)
        self.label_3.setBuddy(self.byte_order)
        self.label_5.setBuddy(self.conn_serial_port)
        self.label_6.setBuddy(self.conn_serial_baudrate)
        self.label_8.setBuddy(self.conn_serial_port)
        self.label_7.setBuddy(self.conn_serial_port)

        self.retranslateUi(InstrumentEditorMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pf_rx_format_1.setCurrentIndex(1)
        self.pf_rx_format_2.setCurrentIndex(2)
        self.pf_rx_format_3.setCurrentIndex(3)
        self.pf_tx_format_1.setCurrentIndex(1)
        self.pf_tx_format_2.setCurrentIndex(2)
        self.pf_tx_format_3.setCurrentIndex(3)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("triggered()")), InstrumentEditorMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(InstrumentEditorMainWindow)

    def retranslateUi(self, InstrumentEditorMainWindow):
        InstrumentEditorMainWindow.setWindowTitle(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Instrument Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Instrument Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Short name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Byte Order", None, QtGui.QApplication.UnicodeUTF8))
        self.byte_order.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "big-endian", None, QtGui.QApplication.UnicodeUTF8))
        self.byte_order.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "little-endian", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_type.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_type.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_type.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_serial_group.setTitle(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Serial Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Baudrate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Data bits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Stop bits", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_tcp_group.setTitle(QtGui.QApplication.translate("InstrumentEditorMainWindow", "TCP Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_file_group.setTitle(QtGui.QApplication.translate("InstrumentEditorMainWindow", "File Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "File name", None, QtGui.QApplication.UnicodeUTF8))
        self.conn_file_name_btn.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connection), QtGui.QApplication.translate("InstrumentEditorMainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "rx packets format:", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_0.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_0.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_0.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_0.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_0.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_1.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_1.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_1.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_1.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_1.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_2.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_2.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_2.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_2.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_2.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_3.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_3.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_3.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_3.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_rx_format_3.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "tx packets format:", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_0.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_0.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_0.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_0.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_0.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_1.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_1.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_1.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_1.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_1.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_2.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_2.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_2.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_2.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_2.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_3.setItemText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_3.setItemText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet num", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_3.setItemText(2, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet fields", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_3.setItemText(3, QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_tx_format_3.setItemText(4, QtGui.QApplication.translate("InstrumentEditorMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Start bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_add_start_byte.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Add new...", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_delete_start_byte.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "End bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_add_end_byte.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Add new...", None, QtGui.QApplication.UnicodeUTF8))
        self.pf_delete_end_byte.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.packet_format), QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet Format", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_add.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_delete.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.packetNumberLabel.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_num.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "num_packet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_fields.headerItem().setText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_fields.headerItem().setText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_add_field.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Add new...", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_packets_delete_field.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rx_packets), QtGui.QApplication.translate("InstrumentEditorMainWindow", "Rx Packets", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_add.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_delete.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Packet", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_num.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "num_packet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_fields.headerItem().setText(0, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_fields.headerItem().setText(1, QtGui.QApplication.translate("InstrumentEditorMainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_add_field.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Add new...", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_packets_delete_field.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tx_packets), QtGui.QApplication.translate("InstrumentEditorMainWindow", "Tx Packets", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setShortcut(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("InstrumentEditorMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("InstrumentEditorMainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    InstrumentEditorMainWindow = QtGui.QMainWindow()
    ui = Ui_InstrumentEditorMainWindow()
    ui.setupUi(InstrumentEditorMainWindow)
    InstrumentEditorMainWindow.show()
    sys.exit(app.exec_())

