# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pau/feina/UPC/projecte/code/GDAIS/ui/equipmenteditor_mainwindow.ui'
#
# Created: Tue Mar  8 11:56:17 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_EquipmentEditorMainWindow(object):
    def setupUi(self, EquipmentEditorMainWindow):
        EquipmentEditorMainWindow.setObjectName(_fromUtf8("EquipmentEditorMainWindow"))
        EquipmentEditorMainWindow.resize(724, 697)
        self.centralWidget = QtGui.QWidget(EquipmentEditorMainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.equipment_name = QtGui.QLineEdit(self.centralWidget)
        self.equipment_name.setText(_fromUtf8(""))
        self.equipment_name.setObjectName(_fromUtf8("equipment_name"))
        self.horizontalLayout_7.addWidget(self.equipment_name)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.equipment_short_name = QtGui.QLineEdit(self.centralWidget)
        self.equipment_short_name.setObjectName(_fromUtf8("equipment_short_name"))
        self.horizontalLayout_7.addWidget(self.equipment_short_name)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.instruments_list = QtGui.QListWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruments_list.sizePolicy().hasHeightForWidth())
        self.instruments_list.setSizePolicy(sizePolicy)
        self.instruments_list.setMaximumSize(QtCore.QSize(120, 16777215))
        self.instruments_list.setObjectName(_fromUtf8("instruments_list"))
        self.verticalLayout_7.addWidget(self.instruments_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.instruments_add = QtGui.QPushButton(self.centralWidget)
        self.instruments_add.setObjectName(_fromUtf8("instruments_add"))
        self.horizontalLayout_12.addWidget(self.instruments_add)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.instruments_delete = QtGui.QPushButton(self.centralWidget)
        self.instruments_delete.setEnabled(False)
        self.instruments_delete.setObjectName(_fromUtf8("instruments_delete"))
        self.horizontalLayout_12.addWidget(self.instruments_delete)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.line_4 = QtGui.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.instrument_name = QtGui.QLabel(self.centralWidget)
        self.instrument_name.setObjectName(_fromUtf8("instrument_name"))
        self.horizontalLayout_3.addWidget(self.instrument_name)
        spacerItem4 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.init_commands_tab = QtGui.QWidget()
        self.init_commands_tab.setObjectName(_fromUtf8("init_commands_tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.init_commands_tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.init_commands_list = QtGui.QListWidget(self.init_commands_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_commands_list.sizePolicy().hasHeightForWidth())
        self.init_commands_list.setSizePolicy(sizePolicy)
        self.init_commands_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.init_commands_list.setObjectName(_fromUtf8("init_commands_list"))
        self.verticalLayout_3.addWidget(self.init_commands_list)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.init_commands_add = QtGui.QPushButton(self.init_commands_tab)
        self.init_commands_add.setObjectName(_fromUtf8("init_commands_add"))
        self.horizontalLayout_13.addWidget(self.init_commands_add)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.init_commands_delete = QtGui.QPushButton(self.init_commands_tab)
        self.init_commands_delete.setEnabled(False)
        self.init_commands_delete.setObjectName(_fromUtf8("init_commands_delete"))
        self.horizontalLayout_13.addWidget(self.init_commands_delete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.init_command_name = QtGui.QLabel(self.init_commands_tab)
        self.init_command_name.setObjectName(_fromUtf8("init_command_name"))
        self.gridLayout_2.addWidget(self.init_command_name, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.init_command_values = QtGui.QTreeWidget(self.init_commands_tab)
        self.init_command_values.setRootIsDecorated(False)
        self.init_command_values.setObjectName(_fromUtf8("init_command_values"))
        self.init_command_values.header().setDefaultSectionSize(250)
        self.verticalLayout_2.addWidget(self.init_command_values)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.init_commands_tab, _fromUtf8(""))
        self.operation_mode_tab = QtGui.QWidget()
        self.operation_mode_tab.setObjectName(_fromUtf8("operation_mode_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.operation_mode_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.operation_mode_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.operation_mode = QtGui.QComboBox(self.operation_mode_tab)
        self.operation_mode.setObjectName(_fromUtf8("operation_mode"))
        self.operation_mode.addItem(_fromUtf8(""))
        self.operation_mode.addItem(_fromUtf8(""))
        self.operation_mode.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.operation_mode)
        spacerItem7 = QtGui.QSpacerItem(37, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.operation_commands_list = QtGui.QListWidget(self.operation_mode_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation_commands_list.sizePolicy().hasHeightForWidth())
        self.operation_commands_list.setSizePolicy(sizePolicy)
        self.operation_commands_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.operation_commands_list.setObjectName(_fromUtf8("operation_commands_list"))
        self.verticalLayout_4.addWidget(self.operation_commands_list)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.operation_commands_add = QtGui.QPushButton(self.operation_mode_tab)
        self.operation_commands_add.setObjectName(_fromUtf8("operation_commands_add"))
        self.horizontalLayout_14.addWidget(self.operation_commands_add)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.operation_commands_delete = QtGui.QPushButton(self.operation_mode_tab)
        self.operation_commands_delete.setEnabled(False)
        self.operation_commands_delete.setObjectName(_fromUtf8("operation_commands_delete"))
        self.horizontalLayout_14.addWidget(self.operation_commands_delete)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem9 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 1, 1, 1)
        self.operation_command_param_pre_txt = QtGui.QLabel(self.operation_mode_tab)
        self.operation_command_param_pre_txt.setObjectName(_fromUtf8("operation_command_param_pre_txt"))
        self.gridLayout_3.addWidget(self.operation_command_param_pre_txt, 0, 2, 1, 1)
        self.operation_command_param = QtGui.QLineEdit(self.operation_mode_tab)
        self.operation_command_param.setMaximumSize(QtCore.QSize(100, 16777215))
        self.operation_command_param.setObjectName(_fromUtf8("operation_command_param"))
        self.gridLayout_3.addWidget(self.operation_command_param, 0, 3, 1, 1)
        self.operation_command_name = QtGui.QLabel(self.operation_mode_tab)
        self.operation_command_name.setObjectName(_fromUtf8("operation_command_name"))
        self.gridLayout_3.addWidget(self.operation_command_name, 0, 0, 1, 1)
        self.operation_command_param_post_txt = QtGui.QLabel(self.operation_mode_tab)
        self.operation_command_param_post_txt.setObjectName(_fromUtf8("operation_command_param_post_txt"))
        self.gridLayout_3.addWidget(self.operation_command_param_post_txt, 0, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.operation_command_values = QtGui.QTreeWidget(self.operation_mode_tab)
        self.operation_command_values.setRootIsDecorated(False)
        self.operation_command_values.setObjectName(_fromUtf8("operation_command_values"))
        self.operation_command_values.header().setDefaultSectionSize(250)
        self.verticalLayout_5.addWidget(self.operation_command_values)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.operation_mode_tab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        EquipmentEditorMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(EquipmentEditorMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 724, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        EquipmentEditorMainWindow.setMenuBar(self.menuBar)
        self.action_New = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Open = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Save = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Save_As = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Save_As.setObjectName(_fromUtf8("action_Save_As"))
        self.action_Quit = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_About = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_About)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.equipment_name)
        self.label_2.setBuddy(self.equipment_short_name)

        self.retranslateUi(EquipmentEditorMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("triggered()")), EquipmentEditorMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(EquipmentEditorMainWindow)

    def retranslateUi(self, EquipmentEditorMainWindow):
        EquipmentEditorMainWindow.setWindowTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Equipment Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Equipment Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Short name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.instrument_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "instrument_name", None, QtGui.QApplication.UnicodeUTF8))
        self.init_commands_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.init_commands_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.init_commands_tab), QtGui.QApplication.translate("EquipmentEditorMainWindow", "Init Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Select operation mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_mode.setItemText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Periodic Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_mode.setItemText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Time Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_mode.setItemText(2, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Blocking Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_commands_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_commands_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_command_param_pre_txt.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Period:", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_command_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_command_param_post_txt.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_command_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_command_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.operation_mode_tab), QtGui.QApplication.translate("EquipmentEditorMainWindow", "Operation Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EquipmentEditorMainWindow = QtGui.QMainWindow()
    ui = Ui_EquipmentEditorMainWindow()
    ui.setupUi(EquipmentEditorMainWindow)
    EquipmentEditorMainWindow.show()
    sys.exit(app.exec_())

