# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pau/feina/UPC/projecte/code/GDAIS/ui/equipmenteditor_mainwindow.ui'
#
# Created: Tue Feb 22 10:46:01 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EquipmentEditorMainWindow(object):
    def setupUi(self, EquipmentEditorMainWindow):
        EquipmentEditorMainWindow.setObjectName("EquipmentEditorMainWindow")
        EquipmentEditorMainWindow.resize(532, 666)
        self.centralWidget = QtGui.QWidget(EquipmentEditorMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.equipment_name = QtGui.QLineEdit(self.centralWidget)
        self.equipment_name.setText("")
        self.equipment_name.setObjectName("equipment_name")
        self.gridLayout.addWidget(self.equipment_name, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.equipment_short_name = QtGui.QLineEdit(self.centralWidget)
        self.equipment_short_name.setObjectName("equipment_short_name")
        self.gridLayout.addWidget(self.equipment_short_name, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.instruments = QtGui.QWidget()
        self.instruments.setObjectName("instruments")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.instruments)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.instruments_list = QtGui.QListWidget(self.instruments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruments_list.sizePolicy().hasHeightForWidth())
        self.instruments_list.setSizePolicy(sizePolicy)
        self.instruments_list.setMaximumSize(QtCore.QSize(120, 16777215))
        self.instruments_list.setObjectName("instruments_list")
        self.verticalLayout_7.addWidget(self.instruments_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.instruments_add = QtGui.QPushButton(self.instruments)
        self.instruments_add.setObjectName("instruments_add")
        self.horizontalLayout_12.addWidget(self.instruments_add)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.instruments_delete = QtGui.QPushButton(self.instruments)
        self.instruments_delete.setEnabled(False)
        self.instruments_delete.setObjectName("instruments_delete")
        self.horizontalLayout_12.addWidget(self.instruments_delete)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.line_4 = QtGui.QFrame(self.instruments)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.instrument_name = QtGui.QLabel(self.instruments)
        self.instrument_name.setObjectName("instrument_name")
        self.horizontalLayout_3.addWidget(self.instrument_name)
        spacerItem2 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.line_2 = QtGui.QFrame(self.instruments)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtGui.QLabel(self.instruments)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        spacerItem3 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.init_commands_list = QtGui.QListWidget(self.instruments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_commands_list.sizePolicy().hasHeightForWidth())
        self.init_commands_list.setSizePolicy(sizePolicy)
        self.init_commands_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.init_commands_list.setObjectName("init_commands_list")
        self.verticalLayout_3.addWidget(self.init_commands_list)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.init_commands_add = QtGui.QPushButton(self.instruments)
        self.init_commands_add.setObjectName("init_commands_add")
        self.horizontalLayout_13.addWidget(self.init_commands_add)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.init_commands_delete = QtGui.QPushButton(self.instruments)
        self.init_commands_delete.setEnabled(False)
        self.init_commands_delete.setObjectName("init_commands_delete")
        self.horizontalLayout_13.addWidget(self.init_commands_delete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.init_command_name = QtGui.QLabel(self.instruments)
        self.init_command_name.setObjectName("init_command_name")
        self.gridLayout_2.addWidget(self.init_command_name, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.init_command_values = QtGui.QTreeWidget(self.instruments)
        self.init_command_values.setRootIsDecorated(False)
        self.init_command_values.setObjectName("init_command_values")
        self.init_command_values.header().setDefaultSectionSize(250)
        self.verticalLayout_2.addWidget(self.init_command_values)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(self.instruments)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtGui.QLabel(self.instruments)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        spacerItem6 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.periodic_commands_list = QtGui.QListWidget(self.instruments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodic_commands_list.sizePolicy().hasHeightForWidth())
        self.periodic_commands_list.setSizePolicy(sizePolicy)
        self.periodic_commands_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.periodic_commands_list.setObjectName("periodic_commands_list")
        self.verticalLayout_4.addWidget(self.periodic_commands_list)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.periodic_commands_add = QtGui.QPushButton(self.instruments)
        self.periodic_commands_add.setObjectName("periodic_commands_add")
        self.horizontalLayout_14.addWidget(self.periodic_commands_add)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.periodic_commands_delete = QtGui.QPushButton(self.instruments)
        self.periodic_commands_delete.setEnabled(False)
        self.periodic_commands_delete.setObjectName("periodic_commands_delete")
        self.horizontalLayout_14.addWidget(self.periodic_commands_delete)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.instruments)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.periodic_command_period = QtGui.QLineEdit(self.instruments)
        self.periodic_command_period.setObjectName("periodic_command_period")
        self.gridLayout_3.addWidget(self.periodic_command_period, 0, 3, 1, 1)
        self.periodic_command_name = QtGui.QLabel(self.instruments)
        self.periodic_command_name.setObjectName("periodic_command_name")
        self.gridLayout_3.addWidget(self.periodic_command_name, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.periodic_command_values = QtGui.QTreeWidget(self.instruments)
        self.periodic_command_values.setRootIsDecorated(False)
        self.periodic_command_values.setObjectName("periodic_command_values")
        self.periodic_command_values.header().setDefaultSectionSize(250)
        self.verticalLayout_5.addWidget(self.periodic_command_values)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.instruments, "")
        self.periodic_sequences = QtGui.QWidget()
        self.periodic_sequences.setObjectName("periodic_sequences")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.periodic_sequences)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget.addTab(self.periodic_sequences, "")
        self.verticalLayout.addWidget(self.tabWidget)
        EquipmentEditorMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(EquipmentEditorMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 532, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        EquipmentEditorMainWindow.setMenuBar(self.menuBar)
        self.action_New = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_As = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_Quit = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_About = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_About.setObjectName("action_About")
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_About)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.equipment_name)
        self.label_2.setBuddy(self.equipment_short_name)
        self.label_6.setBuddy(self.equipment_short_name)

        self.retranslateUi(EquipmentEditorMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("triggered()"), EquipmentEditorMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(EquipmentEditorMainWindow)

    def retranslateUi(self, EquipmentEditorMainWindow):
        EquipmentEditorMainWindow.setWindowTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Equipment Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Equipment Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Short name", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.instrument_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "instrument_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Init Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.init_commands_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.init_commands_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Periodic Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_commands_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_commands_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Period", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_command_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_command_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_command_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.instruments), QtGui.QApplication.translate("EquipmentEditorMainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.periodic_sequences), QtGui.QApplication.translate("EquipmentEditorMainWindow", "Periodic Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EquipmentEditorMainWindow = QtGui.QMainWindow()
    ui = Ui_EquipmentEditorMainWindow()
    ui.setupUi(EquipmentEditorMainWindow)
    EquipmentEditorMainWindow.show()
    sys.exit(app.exec_())

