# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pau/feina/UPC/projecte/code/GDAIS/ui/equipmenteditor_mainwindow.ui'
#
# Created: Thu Mar  3 12:01:18 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EquipmentEditorMainWindow(object):
    def setupUi(self, EquipmentEditorMainWindow):
        EquipmentEditorMainWindow.setObjectName("EquipmentEditorMainWindow")
        EquipmentEditorMainWindow.resize(622, 581)
        self.centralWidget = QtGui.QWidget(EquipmentEditorMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.equipment_name = QtGui.QLineEdit(self.centralWidget)
        self.equipment_name.setText("")
        self.equipment_name.setObjectName("equipment_name")
        self.horizontalLayout_7.addWidget(self.equipment_name)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.equipment_short_name = QtGui.QLineEdit(self.centralWidget)
        self.equipment_short_name.setObjectName("equipment_short_name")
        self.horizontalLayout_7.addWidget(self.equipment_short_name)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.instruments_list = QtGui.QListWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruments_list.sizePolicy().hasHeightForWidth())
        self.instruments_list.setSizePolicy(sizePolicy)
        self.instruments_list.setMaximumSize(QtCore.QSize(120, 16777215))
        self.instruments_list.setObjectName("instruments_list")
        self.verticalLayout_7.addWidget(self.instruments_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.instruments_add = QtGui.QPushButton(self.centralWidget)
        self.instruments_add.setObjectName("instruments_add")
        self.horizontalLayout_12.addWidget(self.instruments_add)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.instruments_delete = QtGui.QPushButton(self.centralWidget)
        self.instruments_delete.setEnabled(False)
        self.instruments_delete.setObjectName("instruments_delete")
        self.horizontalLayout_12.addWidget(self.instruments_delete)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.line_4 = QtGui.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.instrument_name = QtGui.QLabel(self.centralWidget)
        self.instrument_name.setObjectName("instrument_name")
        self.horizontalLayout_3.addWidget(self.instrument_name)
        spacerItem4 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.init_commands_tab = QtGui.QWidget()
        self.init_commands_tab.setObjectName("init_commands_tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.init_commands_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.init_commands_list = QtGui.QListWidget(self.init_commands_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_commands_list.sizePolicy().hasHeightForWidth())
        self.init_commands_list.setSizePolicy(sizePolicy)
        self.init_commands_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.init_commands_list.setObjectName("init_commands_list")
        self.verticalLayout_3.addWidget(self.init_commands_list)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.init_commands_add = QtGui.QPushButton(self.init_commands_tab)
        self.init_commands_add.setObjectName("init_commands_add")
        self.horizontalLayout_13.addWidget(self.init_commands_add)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.init_commands_delete = QtGui.QPushButton(self.init_commands_tab)
        self.init_commands_delete.setEnabled(False)
        self.init_commands_delete.setObjectName("init_commands_delete")
        self.horizontalLayout_13.addWidget(self.init_commands_delete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.init_command_name = QtGui.QLabel(self.init_commands_tab)
        self.init_command_name.setObjectName("init_command_name")
        self.gridLayout_2.addWidget(self.init_command_name, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.init_command_values = QtGui.QTreeWidget(self.init_commands_tab)
        self.init_command_values.setRootIsDecorated(False)
        self.init_command_values.setObjectName("init_command_values")
        self.init_command_values.header().setDefaultSectionSize(250)
        self.verticalLayout_2.addWidget(self.init_command_values)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.init_commands_tab, "")
        self.operation_mode_tab = QtGui.QWidget()
        self.operation_mode_tab.setObjectName("operation_mode_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.operation_mode_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtGui.QLabel(self.operation_mode_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.operation_mode = QtGui.QComboBox(self.operation_mode_tab)
        self.operation_mode.setObjectName("operation_mode")
        self.operation_mode.addItem("")
        self.operation_mode.addItem("")
        self.operation_mode.addItem("")
        self.horizontalLayout_5.addWidget(self.operation_mode)
        spacerItem7 = QtGui.QSpacerItem(37, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.operation_mode_stack = QtGui.QStackedWidget(self.operation_mode_tab)
        self.operation_mode_stack.setObjectName("operation_mode_stack")
        self.periodic_commands_page = QtGui.QWidget()
        self.periodic_commands_page.setObjectName("periodic_commands_page")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.periodic_commands_page)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.periodic_commands_list = QtGui.QListWidget(self.periodic_commands_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodic_commands_list.sizePolicy().hasHeightForWidth())
        self.periodic_commands_list.setSizePolicy(sizePolicy)
        self.periodic_commands_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.periodic_commands_list.setObjectName("periodic_commands_list")
        self.verticalLayout_4.addWidget(self.periodic_commands_list)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.periodic_commands_add = QtGui.QPushButton(self.periodic_commands_page)
        self.periodic_commands_add.setObjectName("periodic_commands_add")
        self.horizontalLayout_14.addWidget(self.periodic_commands_add)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.periodic_commands_delete = QtGui.QPushButton(self.periodic_commands_page)
        self.periodic_commands_delete.setEnabled(False)
        self.periodic_commands_delete.setObjectName("periodic_commands_delete")
        self.horizontalLayout_14.addWidget(self.periodic_commands_delete)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem9 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.periodic_commands_page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.periodic_command_period = QtGui.QLineEdit(self.periodic_commands_page)
        self.periodic_command_period.setObjectName("periodic_command_period")
        self.gridLayout_3.addWidget(self.periodic_command_period, 0, 3, 1, 1)
        self.periodic_command_name = QtGui.QLabel(self.periodic_commands_page)
        self.periodic_command_name.setObjectName("periodic_command_name")
        self.gridLayout_3.addWidget(self.periodic_command_name, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.periodic_commands_page)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.periodic_command_values = QtGui.QTreeWidget(self.periodic_commands_page)
        self.periodic_command_values.setRootIsDecorated(False)
        self.periodic_command_values.setObjectName("periodic_command_values")
        self.periodic_command_values.header().setDefaultSectionSize(250)
        self.verticalLayout_5.addWidget(self.periodic_command_values)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.operation_mode_stack.addWidget(self.periodic_commands_page)
        self.time_sequences_page = QtGui.QWidget()
        self.time_sequences_page.setObjectName("time_sequences_page")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.time_sequences_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.time_sequences_list = QtGui.QListWidget(self.time_sequences_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_sequences_list.sizePolicy().hasHeightForWidth())
        self.time_sequences_list.setSizePolicy(sizePolicy)
        self.time_sequences_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.time_sequences_list.setObjectName("time_sequences_list")
        self.verticalLayout_10.addWidget(self.time_sequences_list)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.time_sequences_add = QtGui.QPushButton(self.time_sequences_page)
        self.time_sequences_add.setObjectName("time_sequences_add")
        self.horizontalLayout_15.addWidget(self.time_sequences_add)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.time_sequences_delete = QtGui.QPushButton(self.time_sequences_page)
        self.time_sequences_delete.setEnabled(False)
        self.time_sequences_delete.setObjectName("time_sequences_delete")
        self.horizontalLayout_15.addWidget(self.time_sequences_delete)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem11 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.time_sequences_page)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 2, 1, 1)
        self.time_sequence_duration = QtGui.QLineEdit(self.time_sequences_page)
        self.time_sequence_duration.setObjectName("time_sequence_duration")
        self.gridLayout_4.addWidget(self.time_sequence_duration, 0, 3, 1, 1)
        self.time_sequence_name = QtGui.QLabel(self.time_sequences_page)
        self.time_sequence_name.setObjectName("time_sequence_name")
        self.gridLayout_4.addWidget(self.time_sequence_name, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.time_sequences_page)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.time_sequence_values = QtGui.QTreeWidget(self.time_sequences_page)
        self.time_sequence_values.setRootIsDecorated(False)
        self.time_sequence_values.setObjectName("time_sequence_values")
        self.time_sequence_values.header().setDefaultSectionSize(250)
        self.verticalLayout_9.addWidget(self.time_sequence_values)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.operation_mode_stack.addWidget(self.time_sequences_page)
        self.blocking_sequences_page = QtGui.QWidget()
        self.blocking_sequences_page.setObjectName("blocking_sequences_page")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.blocking_sequences_page)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.blocking_sequences_list = QtGui.QListWidget(self.blocking_sequences_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocking_sequences_list.sizePolicy().hasHeightForWidth())
        self.blocking_sequences_list.setSizePolicy(sizePolicy)
        self.blocking_sequences_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.blocking_sequences_list.setObjectName("blocking_sequences_list")
        self.verticalLayout_12.addWidget(self.blocking_sequences_list)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.blocking_sequences_add = QtGui.QPushButton(self.blocking_sequences_page)
        self.blocking_sequences_add.setObjectName("blocking_sequences_add")
        self.horizontalLayout_16.addWidget(self.blocking_sequences_add)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.blocking_sequences_delete = QtGui.QPushButton(self.blocking_sequences_page)
        self.blocking_sequences_delete.setEnabled(False)
        self.blocking_sequences_delete.setObjectName("blocking_sequences_delete")
        self.horizontalLayout_16.addWidget(self.blocking_sequences_delete)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem13 = QtGui.QSpacerItem(100, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.blocking_sequences_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 2, 1, 1)
        self.blocking_sequence_repeat = QtGui.QLineEdit(self.blocking_sequences_page)
        self.blocking_sequence_repeat.setObjectName("blocking_sequence_repeat")
        self.gridLayout_5.addWidget(self.blocking_sequence_repeat, 0, 3, 1, 1)
        self.blocking_sequence_name = QtGui.QLabel(self.blocking_sequences_page)
        self.blocking_sequence_name.setObjectName("blocking_sequence_name")
        self.gridLayout_5.addWidget(self.blocking_sequence_name, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.blocking_sequences_page)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 4, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_5)
        self.blocking_sequence_values = QtGui.QTreeWidget(self.blocking_sequences_page)
        self.blocking_sequence_values.setRootIsDecorated(False)
        self.blocking_sequence_values.setObjectName("blocking_sequence_values")
        self.blocking_sequence_values.header().setDefaultSectionSize(250)
        self.verticalLayout_11.addWidget(self.blocking_sequence_values)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.operation_mode_stack.addWidget(self.blocking_sequences_page)
        self.verticalLayout.addWidget(self.operation_mode_stack)
        self.tabWidget.addTab(self.operation_mode_tab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        EquipmentEditorMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(EquipmentEditorMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 622, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        EquipmentEditorMainWindow.setMenuBar(self.menuBar)
        self.action_New = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_As = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_Quit = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_About = QtGui.QAction(EquipmentEditorMainWindow)
        self.action_About.setObjectName("action_About")
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_About)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.equipment_name)
        self.label_2.setBuddy(self.equipment_short_name)

        self.retranslateUi(EquipmentEditorMainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("triggered()"), EquipmentEditorMainWindow.close)
        QtCore.QObject.connect(self.operation_mode, QtCore.SIGNAL("activated(int)"), self.operation_mode_stack.setCurrentIndex)
        QtCore.QObject.connect(self.operation_mode_stack, QtCore.SIGNAL("currentChanged(int)"), self.operation_mode.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(EquipmentEditorMainWindow)

    def retranslateUi(self, EquipmentEditorMainWindow):
        EquipmentEditorMainWindow.setWindowTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Equipment Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Equipment Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Short name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.instruments_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.instrument_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "instrument_name", None, QtGui.QApplication.UnicodeUTF8))
        self.init_commands_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.init_commands_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.init_command_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.init_commands_tab), QtGui.QApplication.translate("EquipmentEditorMainWindow", "Init Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Select operation mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_mode.setItemText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Periodic Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_mode.setItemText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Time Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.operation_mode.setItemText(2, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Blocking Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_commands_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_commands_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Period:", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_command_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_command_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.periodic_command_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.time_sequences_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.time_sequences_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_sequence_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.time_sequence_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.time_sequence_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.blocking_sequences_add.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.blocking_sequences_delete.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Repeat:", None, QtGui.QApplication.UnicodeUTF8))
        self.blocking_sequence_name.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "command_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "times", None, QtGui.QApplication.UnicodeUTF8))
        self.blocking_sequence_values.headerItem().setText(0, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.blocking_sequence_values.headerItem().setText(1, QtGui.QApplication.translate("EquipmentEditorMainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.operation_mode_tab), QtGui.QApplication.translate("EquipmentEditorMainWindow", "Operation Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("EquipmentEditorMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("EquipmentEditorMainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EquipmentEditorMainWindow = QtGui.QMainWindow()
    ui = Ui_EquipmentEditorMainWindow()
    ui.setupUi(EquipmentEditorMainWindow)
    EquipmentEditorMainWindow.show()
    sys.exit(app.exec_())

